# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title standard Laplace distribution
#' @description Implement a random walk Metropolis sampler for generating the standard Laplace distribution
#' @param a variance
#' @param xx the initial value
#' @param  N length of the chain
#' @return a random walk of the standard Laplace distribution
#' @examples
#' \dontrun{
#' cla(1,0,2000)
#' }
#' @export
cla <- function(a, xx, N) {
    .Call('_StatComp_cla', PACKAGE = 'StatComp', a, xx, N)
}

